### ISSUE TITLE
Item duplication bug

### ISSUE THREAD

**Issue by CentaurPrime** [Ada18980/KinkiestDungeon#91]
I recall seeing a changelog regarding an attempt to resolve an item duplication bug. However, I believe this bug is present in version 5.0.7(F) on itch.io.  A save file which can reproduce the issue is attached as [kd.json.dmp](https://github.com/Ada18980/KinkiestDungeon/files/13910868/kd.json.dmp).

Steps to Reproduce:
* Load the save file via copy/paste.
* Examine the `Restraints` section of the Player's inventory. Note that there is a stack of 11 objects of type `Obsidian Muzzle` and 7 objects/stacks matching the `Special` filter.
* Pick/unlock the worn`Obsidian Muzzle`.
* Remove the worn `Obsidian Muzzle`.
* Again, examine the `Restraints` section of the Player's inventory. Note that the stack of objects of type `Obsidian Muzzle` still only contains 11 objects, but there are now 9 objects/stacks matching the `Special` filter. The two newly added objects match the remainder of the item stack in that slot (a `High-Security Muzzle of Resistance` and an `Enchanted High-Security Ball Gag`).

**Comment by Ada18980** [comment]
I think this has been resolved in 5.1, I hope at least

**Comment by CentaurPrime** [comment]
I've walked through the test case using the 5.1.14 version on itch.io, and it still appears to be present. I also ran into another trigger path, but I don't have a formal test case for it. I received a quest reward which was curse locked by the granting goddess (Illusions). When I approached her shrine, it was removed and two copies were generated in inventory.

**Comment by CentaurPrime** [comment]
Tested with version 5.2.20 on itch.io, and appears to be fixed.
